### ISSUE TITLE
English locale file still contains French messages

### ISSUE THREAD

**Issue by necramirez** [jbox-web/redmine_git_hosting#334]
I've only encountered this:  https://github.com/jbox-web/redmine_git_hosting/blob/devel/config/locales/models/repository_xitolite/en.yml#L10-L16
```
                blank_default_exists: "Ne peut pas mettre le dépôt par défaut, car le dépôt par défaut courant a un identifiant vide."
                  invalid_options: "Vous ne pouvez pas initialiser de fichier README dans un dépot GitAnnex"
                identifier:
                  cannot_equal_project: "ne peut pas correspondre à l'identifiant d'un projet existant"
                  taken: "correspond à un identifiant de dépôt existant"
                  invalid: invalide
                  cannot_change: ne peut pas changer
```
I haven't checked the other locale files yet.

**Comment by n-rodriguez** [comment]
I'm gonna update translations.
Thank you!

**Comment by wilsoc5** [comment]
May I ask why french translations are in the English locale file if this ticket is closed?

**Comment by n-rodriguez** [comment]
Maybe because I'm a human and I may have forgotten to update the translation file... Feel free to propose a patch :)

**Comment by wilsoc5** [comment]
````
 repository/xitolite:
          attributes:
            base:
              blank_default_exists: "Can not create the respository as a blank repository already exists."
              invalid_options: "You can not initialize a README file in a repository with GitAnnex"
            identifier:
              cannot_equal_project: "can not match the ID of an existing project"
              taken: "is already taken."
              invalid: invalid
              cannot_change: cannot change
`````
